---
# Configure http users
- htpasswd:
    path: "{{httpusers.value.file|default(
        '{0}/htpasswd.{1}'.format(
            cops_www_vars.http_passwd_prefix, httpusers.key))}}"
    name: "{{user.user}}"
    password: "{{user.password}}"
    state: present
  loop: "{{httpusers.value.users}}"
  loop_control: {loop_var: user}
