---
# generate the app vhost(s) before nginx install itself
# as if we have syntax errors, we wont have any chance to regenerate the
# vhost before the general service role will run (syntax check -> deploy KO)
- name: Generate default virtualhost
  include_role:
    name: "corpusops.roles/nginx_default_vhost"
  vars:
    _corpusops_nginx_default_vhost:
      is_default_server: "{{
          cops_www_vars.default_vhost_is_default_server}}"
      check_config: false
  tags: [cops_www_s_setup_reverse_proxy_dvhost]
  when: [cops_www_s_setup_reverse_proxy_dvhost]

- name: Generate APP other virtualhost
  include_tasks: _render_vhost.yml
  with_items: "{{cops_www_vars.vhosts}}"
  loop_control: {loop_var: other_vhost}
  tags: ["cops_www_s_setup_reverse_proxy_vhosts"]
  when: ["cops_www_s_setup_reverse_proxy_vhosts",
         "cops_www_vhosts|copsf_bool"]

# Configure http users
- include_tasks: _htpasswd.yml
  with_dict: "{{cops_www_vars.http_users}}"
  loop_control: {loop_var: httpusers}
  when: ["cops_www_s_setup_reverse_proxy_users and (
            cops_www_vars.http_users is not none and
            cops_www_vars.http_users|length > 0)"]
  tags: [cops_www_s_setup_reverse_proxy_users]
