---
version: '3.5'
# Build with:
#  docker build --squash -t corpusops/www -f Dockerfile [--build-arg=SKIP_COPS_UPDATE=y]
# Start with:
#  docker-compose -f d*-compose.yml -f d*-compose-project.yml up -t 0 -d --force-recreate www
x-image: &image_template
  environment:
  - |
    A_RECONFIGURE=---
    ---
    cops_www_docker_has_front_haproxy: true
    cops_www_docker_has_nginx: true
    cops_www_docker_has_zeo: true
    cops_www_docker_has_www: true
    only_steps: true
    cops_www_lifecycle_app_push_code: false
    cops_www_s_docker_reconfigure: true
    cops_www_s_setup_configs: true
    cops_www_s_setup_reverse_proxy: true
    corpusops_services_proxy_haproxy_do_prerequisites: false
    corpusops_services_proxy_haproxy_do_services: false
  - |
    A_POSTCONFIGURE=---
    ---
    only_steps: true
    corpusops_services_proxy_haproxy_do_prerequisites: false
    corpusops_services_proxy_haproxy_do_services: false
    cops_www_lifecycle_app_push_code: false
    cops_www_s_manage_content: true
  command: >
    sh -c 'if [ "x$DOCKER_SKIP_START" != x ];
    then while true;do echo sleeping;sleep 65535;done
    else exec /app_entry_point;
    fi'
  # for now this is a bloat image-as-a-vm to make a dev env ligther than a vagrant VM
  tmpfs: [/run, /run/lock]
  volumes: &image_volumes
  # systemd
  - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  # data
  - "./local/setup:/setup"
  - "./local/data/blobstorage/storage:/srv/projects/wwwproject/data/var/blobstorage/storage"
  - "./local/data/blobstorage/backup:/srv/projects/wwwproject/data/var/blobstorage/backup"
  - "./local/data/filestorage:/srv/projects/wwwproject/data/var/filestorage"
  - "./local/data/backups:/srv/projects/wwwproject/data/var/backups"
  - "./local/data/snapshotbackups:/srv/projects/wwwproject/data/var/snapshotbackups"
  - "./local/data/log:/srv/projects/wwwproject/data/var/log"
  # Remember: /setup/rootfs/ is synced inside the container /
services:
  www:
    <<:  [ *image_template ]
