---
- include_role: {name: corpusops.roles/configs, private: true}
  vars: {cops_configs_templates: "{{cops_www_vars.ep_configs}}"}
  tags: [cops_www_s_entry_point_configs]
  when: [cops_www_s_entry_point_configs]
- cops_service:
    enabled: "{{cops_www_vars.activated | ternary(True, False)}}"
    daemon_reload: yes
    name: "{{item}}"
  with_items: "{{cops_www_vars.reconfigure_services}}"
  tags: [cops_www_s_entry_point_services]
  when: [cops_www_s_entry_point_services]
