---
- when: ["cops_www_s_workers_service"]
  tags: ["cops_www_s_workers_service"]
  block:
  # activate the main app service
  - cops_service:
      state: "{{cops_www_vars.activated | ternary('started', 'stopped')}}"
      enabled: "{{cops_www_vars.activated | ternary(True, False)}}"
      daemon_reload: yes
      name: "{{item}}"
    with_items: "{{cops_www_vars.services}}"
  # force a reload/restart here
  - shell: echo "force service reload/restart"
    notify: "{{cops_www_vars.rhandlers}}"
  - meta: flush_handlers
