---
- include_role: {name: corpusops.roles/vars, allow_duplicates: false}
- include_role: {name: www_steps, allow_duplicates: false}
# compute some defaults
- set_fact:
    cacheable: false
    # Set absolute path to app role (for templates path)
    cops_www_vrole_path: "{{role_path.replace('_vars', '')}}"

# Generate passwords on remote box if not found in registry
- name: "www secrets -- {{wwwsecret}}}"
  loop_control: {loop_var: secretvariable}
  loop: "{{cops_www_secret_variables}}"
  no_log: "{{not (cops_vars_debug|default(false))}}"
  include_tasks: _set_secret_variable.yml

# Set the cops_www_vars var from defaults/main.yml
- name: "www registry init"
  include_role: {name: corpusops.roles/vars_registry}
  vars: {cops_vars_registry_target: cops_www}
  no_log: "{{not (cops_vars_debug|default(false))}}"

# Post process some variables
- name: "www registry - postprocess"
  include_jinja_vars:
    content: |
      ---
      {% set p = 'cops_www_vars' %}
      {% set _vars = {p: vars[p]} %}
      {% set env = _vars[p].env %}
      {% set _ = env.update(_vars[p].env_overrides) %}
      {# filter user env #}
      {% for i, val in vars.get('ansible_env', {}).items() %}
      {%  if not i.startswith(
              ('OLDPWD', 'CWD', 'PWD',
               'TERM', 'USER', 'HOME', 'PS1',
               'PATH', 'ANSIBLE', 'SSH', 'LS')) %}
      {%    set _ = env.update({i: val})%}
      {%  endif %}
      {% endfor %}
      {{ _vars | to_json }}
  tags: [www, vars, www_vars]
  no_log: "{{not (cops_vars_debug|default(false))}}"
