---
# Configure nginx itself
- include_role:
    name: "corpusops.roles/services_http_nginx"
  tags: [cops_www_s_reverse_proxy_install]
  when: [cops_www_s_reverse_proxy_install,
         "not cops_www_s_nginx_already_done|default(false)"]

# force reload
- name: Reload nginx
  include_role:
    name: "corpusops.roles/nginx_control"
    allow_duplicates: true
  vars:
    _corpusops_nginx_control:
      state: "{{cops_www_vars.services_nginx_reload_state}}"
  tags: [cops_www_s_reverse_proxy_reload]
  when: [cops_www_s_reverse_proxy_reload]
