---
- tags: [cops_www_lifecycle_app_setup]
  when: [cops_www_lifecycle_app_setup]
  become: "{{cops_www_vars.become}}"
  block:
  - include_role: {name: www_docker_reconfigure, allow_duplicates: false}
    tags: [cops_www_s_docker_reconfigure]
    when: [cops_www_s_docker_reconfigure]
  - include_role: {name: www_users, allow_duplicates: false}
    tags: [cops_www_s_users]
    when: [cops_www_s_users]
  - include_role: {name: www_layout, allow_duplicates: false}
    tags: [cops_www_s_layout]
    when: [cops_www_s_layout]
  - include_role: {name: www_fixperms, allow_duplicates: true}
    tags: [cops_www_s_first_fixperms]
    when: [cops_www_s_first_fixperms]
  - include_role: {name: www_prerequisites, allow_duplicates: false}
    tags: [cops_www_s_prerequisites]
    when: [cops_www_s_prerequisites]
  - include_role: {name: www_setup, allow_duplicates: false}
    tags: [cops_www_s_setup]
    when: [cops_www_s_setup]
  - include_role: {name: www_reverse_proxy, allow_duplicates: false}
    tags: [cops_www_s_reverse_proxy]
    when: [cops_www_s_reverse_proxy]
  - include_role: {name: www_entry_point, allow_duplicates: false}
    tags: [cops_www_s_entry_point]
    when: [cops_www_s_entry_point]
  - include_role: {name: www_workers, allow_duplicates: false}
    tags: [cops_www_s_workers]
    when: [cops_www_s_workers]
  - include_role: {name: www_manage_content, allow_duplicates: false}
    tags: [cops_www_s_manage_content]
    when: [cops_www_s_manage_content]
  - include_role: {name: www_healthchecks, allow_duplicates: false}
    tags: [cops_www_s_healthchecks]
    when: [cops_www_s_healthchecks]
  - include_role: {name: www_fixperms, allow_duplicates: true}
    tags: [cops_www_s_end_fixperms]
    when: [cops_www_s_end_fixperms]
