---
- include_jinja_vars:
    content: |-
      {% set r = {} %}
      {% set _ = r.update({'only_steps': only_steps|default(False)}) %}
      {% set only_steps = r['only_steps'] %}
      #
      {% set _ = r.update({'cops_www_s_docker_reconfigure': cops_www_s_docker_reconfigure|default(False)}) %}
      {% set cops_www_s_docker_reconfigure = r['cops_www_s_docker_reconfigure'] %}
      #
      {% set _ = r.update({'cops_www_lifecycle_app_push_code':         cops_www_lifecycle_app_push_code|default(not only_steps)}) %}
      {% set cops_www_lifecycle_app_push_code = r['cops_www_lifecycle_app_push_code'] %}
      #
      {% set _ = r.update({'only_steps': only_steps|default(False)}) %}
      {% set only_steps = r['only_steps'] %}
      #
      {% set _ = r.update({'cops_www_s_prerequisites_nginxinstall':   cops_www_s_prerequisites_nginxinstall      |default(cops_www_s_prerequisites|default(cops_www_lifecycle_app_prerequisites|default(cops_www_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_www_s_prerequisites_nginxinstall = r['cops_www_s_prerequisites_nginxinstall'] %}
      #
      {% set _ = r.update({'cops_www_s_prerequisites_build_pkgs': cops_www_s_prerequisites_build_pkgs            |default(cops_www_s_prerequisites|default(cops_www_lifecycle_app_prerequisites|default(cops_www_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_www_s_prerequisites_build_pkgs = r['cops_www_s_prerequisites_build_pkgs'] %}
      #
      {% set _ = r.update({'cops_www_s_prerequisites_pkgs': cops_www_s_prerequisites_pkgs            |default(cops_www_s_prerequisites|default(cops_www_lifecycle_app_prerequisites|default(cops_www_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_www_s_prerequisites_pkgs = r['cops_www_s_prerequisites_pkgs'] %}
      #
      {% set _ = r.update({'cops_www_s_setup_configs':    cops_www_s_setup_configs                                                                         |default(cops_www_s_setup|default(cops_www_lifecycle_app_setup|default(not only_steps)))}) %}
      {% set cops_www_s_setup_configs = r['cops_www_s_setup_configs'] %}
      #
      {% set _ = r.update({'cops_www_s_setup_hosts':      cops_www_s_setup_hosts                                                                           |default(cops_www_s_setup|default(cops_www_lifecycle_app_setup|default(not only_steps)))}) %}
      {% set cops_www_s_setup_hosts = r['cops_www_s_setup_hosts'] %}
      #
      {% set _ = r.update({'cops_www_s_setup_app':        cops_www_s_setup_app                                                                             |default(cops_www_s_setup|default(cops_www_lifecycle_app_setup|default(not only_steps)))}) %}
      {% set cops_www_s_setup_app = r['cops_www_s_setup_app'] %}
      #
      {% set _ = r.update({'cops_www_s_layout_layout':  cops_www_s_layout_layout|default(cops_www_s_layout         |default(cops_www_lifecycle_app_layout|default(cops_www_s_setup|default(cops_www_lifecycle_app_setup|default(not only_steps)))))}) %}
      {% set cops_www_s_layout_layout = r['cops_www_s_layout_layout'] %}
      #
      {% set _ = r.update({'cops_www_s_setup_reverse_proxy_dvhost':      cops_www_s_setup_reverse_proxy_dvhost     |default(cops_www_s_setup_reverse_proxy|default(cops_www_s_setup|default(cops_www_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_www_s_setup_reverse_proxy_dvhost = r['cops_www_s_setup_reverse_proxy_dvhost'] %}
      #
      {% set _ = r.update({'cops_www_s_setup_reverse_proxy_vhosts':       cops_www_s_setup_reverse_proxy_vhosts      |default(cops_www_s_setup_reverse_proxy|default(cops_www_s_setup|default(cops_www_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_www_s_setup_reverse_proxy_vhosts = r['cops_www_s_setup_reverse_proxy_vhosts'] %}
      #
      {% set _ = r.update({'cops_www_s_setup_reverse_proxy_vhost':       cops_www_s_setup_reverse_proxy_vhost      |default(cops_www_s_setup_reverse_proxy|default(cops_www_s_setup|default(cops_www_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_www_s_setup_reverse_proxy_vhost = r['cops_www_s_setup_reverse_proxy_vhost'] %}
      #
      {% set _ = r.update({'cops_www_s_setup_reverse_proxy_front_vhost': cops_www_s_setup_reverse_proxy_front_vhost|default(cops_www_s_setup_reverse_proxy|default(cops_www_s_setup|default(cops_www_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_www_s_setup_reverse_proxy_front_vhost = r['cops_www_s_setup_reverse_proxy_front_vhost'] %}
      #
      {% set _ = r.update({'cops_www_s_setup_reverse_proxy_users':       cops_www_s_setup_reverse_proxy_users      |default(cops_www_s_setup_reverse_proxy|default(cops_www_s_setup|default(cops_www_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_www_s_setup_reverse_proxy_users = r['cops_www_s_setup_reverse_proxy_users'] %}
      #
      {% set _ = r.update({'cops_www_s_reverse_proxy_install':       cops_www_s_reverse_proxy_install                                              |default(cops_www_s_reverse_proxy|default(cops_www_lifecycle_app_setup|default(not only_steps)))}) %}
      {% set cops_www_s_reverse_proxy_install = r['cops_www_s_reverse_proxy_install'] %}
      #
      {% set _ = r.update({'cops_www_s_reverse_proxy_reload':        cops_www_s_reverse_proxy_reload                                               |default(cops_www_s_reverse_proxy|default(cops_www_lifecycle_app_setup|default(not only_steps)))}) %}
      {% set cops_www_s_reverse_proxy_reload = r['cops_www_s_reverse_proxy_reload'] %}
      #
      {% set _ = r.update({'cops_www_s_fixperms_configs':   cops_www_s_fixperms_configs|default((cops_www_s_first_fixperms|default(not only_steps)) or (cops_www_s_end_fixperms|default(not only_steps)))}) %}
      {% set cops_www_s_fixperms_configs = r['cops_www_s_fixperms_configs'] %}
      #
      {% set _ = r.update({'cops_www_s_fixperms_run':       cops_www_s_fixperms_run    |default((cops_www_s_first_fixperms|default(not only_steps)) or (cops_www_s_end_fixperms|default(not only_steps)))}) %}
      {% set cops_www_s_fixperms_run = r['cops_www_s_fixperms_run'] %}
      #
      {% set _ = r.update({'cops_www_s_first_fixperms': cops_www_s_first_fixperms|default(not only_steps)}) %}
      {% set cops_www_s_first_fixperms = r['cops_www_s_first_fixperms'] %}
      #
      {% set _ = r.update({'cops_www_s_end_fixperms':   cops_www_s_end_fixperms  |default(not only_steps)}) %}
      {% set cops_www_s_end_fixperms = r['cops_www_s_end_fixperms'] %}
      #
      {% set _ = r.update({'cops_www_s_workers_service':      cops_www_s_workers_service     |default(cops_www_s_workers|default(cops_www_lifecycle_app_setup|default(not only_steps)))}) %}
      {% set cops_www_s_workers_service = r['cops_www_s_workers_service'] %}
      #
      {% set _ = r.update({'cops_www_s_entry_point_configs':  cops_www_s_entry_point_configs    |default(cops_www_s_entry_point|default(cops_www_lifecycle_app_setup|default(not only_steps))) and ansible_virtualization_type in ['docker']}) %}
      {% set cops_www_s_entry_point_configs = r['cops_www_s_entry_point_configs'] %}
      #
      {% set _ = r.update({'cops_www_s_entry_point_services':  cops_www_s_entry_point_services  |default(cops_www_s_entry_point|default(cops_www_lifecycle_app_setup|default(not only_steps))) and ansible_virtualization_type in ['docker']}) %}
      {% set cops_www_s_entry_point_services = r['cops_www_s_entry_point_services'] %}
      #
      {% set _ = r.update({'cops_www_s_users_group': cops_www_s_users_group |default(cops_www_s_first_fixperms or cops_www_s_end_fixperms or cops_www_lifecycle_app_push_code or cops_www_s_users|default(cops_www_lifecycle_app_setup|default(not only_steps)))}) %}
      {% set cops_www_s_users_group = r['cops_www_s_users_group'] %}
      #
      {% set _ = r.update({'cops_www_s_users_user':  cops_www_s_users_user  |default(cops_www_s_first_fixperms or cops_www_s_end_fixperms or cops_www_lifecycle_app_push_code or cops_www_s_users|default(cops_www_lifecycle_app_setup|default(not only_steps)))}) %}
      {% set cops_www_s_users_user = r['cops_www_s_users_user'] %}
      #
      {% set _ = r.update({'cops_www_s_users':          cops_www_s_users_group or cops_www_s_users_user}) %}
      {% set cops_www_s_users = r['cops_www_s_users'] %}
      #
      {% set _ = r.update({'cops_www_s_layout':         cops_www_s_layout_layout}) %}
      {% set cops_www_s_layout = r['cops_www_s_layout'] %}
      #
      {% set _ = r.update({'cops_www_s_prerequisites':  ( cops_www_s_prerequisites_nginxinstall or cops_www_s_prerequisites_build_pkgs or cops_www_s_prerequisites_pkgs)}) %}
      {% set cops_www_s_prerequisites = r['cops_www_s_prerequisites'] %}
      #
      {% set _ = r.update({'cops_www_s_workers':        cops_www_s_workers_service}) %}
      {% set cops_www_s_workers = r['cops_www_s_workers'] %}
      #
      {% set _ = r.update({'cops_www_s_entry_point':    (cops_www_s_entry_point_configs or cops_www_s_entry_point_services)}) %}
      {% set cops_www_s_entry_point = r['cops_www_s_entry_point'] %}
      #
      {% set _ = r.update({'cops_www_s_manage_content': cops_www_s_manage_content|default(cops_www_lifecycle_app_setup|default(not only_steps))}) %}
      {% set cops_www_s_manage_content = r['cops_www_s_manage_content'] %}
      #
      {% set _ = r.update({'cops_www_s_setup_reverse_proxy':  ( cops_www_s_setup_reverse_proxy_dvhost or cops_www_s_setup_reverse_proxy_vhosts or cops_www_s_setup_reverse_proxy_vhost or cops_www_s_setup_reverse_proxy_users)}) %}
      {% set cops_www_s_setup_reverse_proxy = r['cops_www_s_setup_reverse_proxy'] %}
      #
      {% set _ = r.update({'cops_www_s_reverse_proxy':  (cops_www_s_reverse_proxy_reload or cops_www_s_reverse_proxy_install)}) %}
      {% set cops_www_s_reverse_proxy = r['cops_www_s_reverse_proxy'] %}
      #
      {% set _ = r.update({'cops_www_s_healthchecks':  cops_www_s_healthchecks  |default(cops_www_lifecycle_app_setup|default(not only_steps))}) %}
      {% set cops_www_s_healthchecks = r['cops_www_s_healthchecks'] %}
      #
      {% set _ = r.update({'cops_www_s_setup': ( cops_www_s_setup_configs or cops_www_s_setup_hosts or cops_www_s_setup_app or cops_www_s_setup_reverse_proxy)}) %}
      {% set cops_www_s_setup = r['cops_www_s_setup'] %}
      #
      {% set _ = r.update({'cops_www_lifecycle_app_level_1_steps': ( cops_www_s_users or cops_www_s_layout or cops_www_s_first_fixperms or cops_www_s_prerequisites or cops_www_s_setup or cops_www_s_reverse_proxy or cops_www_s_workers or cops_www_s_healthchecks or cops_www_s_entry_point or cops_www_s_manage_content or cops_www_s_end_fixperms)}) %}
      {% set cops_www_lifecycle_app_level_1_steps = r['cops_www_lifecycle_app_level_1_steps'] %}
      #
      {% set _ = r.update({'cops_www_lifecycle_app_setup': cops_www_lifecycle_app_setup|default( (cops_www_lifecycle_app|default(False)) or ( cops_www_lifecycle_app_level_1_steps))}) %}
      {% set cops_www_lifecycle_app_setup = r['cops_www_lifecycle_app_setup'] %}
      #
      {% set _ = r.update({'cops_www_lifecycle_app': cops_www_lifecycle_app|default(cops_www_lifecycle_app_push_code or cops_www_lifecycle_app_setup)}) %}
      {% set cops_www_lifecycle_app = r['cops_www_lifecycle_app'] %}
      #
      {% set _ = r.update({'cops_www_lifecycle_lc_1_steps': (cops_www_lifecycle_app)}) %}
      {% set cops_www_lifecycle_lc_1_steps = r['cops_www_lifecycle_lc_1_steps'] %}
      #
      {% set _ = r.update({'cops_www_s_vars': cops_www_s_vars|default(cops_www_lifecycle_lc_1_steps)}) %}
      {% set cops_www_s_vars = r['cops_www_s_vars'] %}
      #
      {{ r|to_json }}
